---

- hosts: neuvector
  remote_user: vagrant
  become: yes
  vars:
    orchestrator: docker
    docker_login:
      username: wikitops
      password: wikitops
      email: wikitops@example.org
  roles:
    - neuvector
